### ISSUE TITLE
Load configuration from `.ubidoc.yml` instead from `build.sbt`

### ISSUE THREAD

**Issue by nicolasfara** [atedeg/sbt-ubiquitous-scaladoc#7]
Since lots of configurations in term of tables, html tags, class to include/exclude, would be better to move out those configs from the `build.sb` in order to reduce his (unnecessarily) verbosity. In order to do this, we could create a configuration file called `.ubidoc.yml`.

The `.ubidoc.yml` could contain the following properties:
  - Header of the table and relative html tags to extract the content
  - The name of the files to parse in order to build the table rows

An example of this `.ubidoc.yml` could be:

```yaml
tables:
  - name: FooBar
    header:
      col1: "title"
      col2: "div > p"
      col3: "p"
    rows: ["Class1", "Class2", "Type1", "Enum1"]

  - name: FooBarBaz
    header:
      col1: "title"
      col2: "div > p"
      col3: "p"
    rows: ["Class3", "Class4", "Type2"]
```

A possible serialization of this file could be:

```scala
final case class TableList(tables: List[Table])
final case class Table(name: String, header: Map[String, String], rows: List[String])
```

Note on the `header` map: it might help to have a pair ("Column title" -> "HTML selector") without the need to check if table columns number matches the html selector. Finally, the map helps to get the right html selector based on the right column.

Talking with @giacomocavalieri we agreed that this approach could be more extensible and convenient.
Moreover, this approach gives us the possibility to define the order of appearance in the table of the definitions, according to the order specified in the `rows` key.

**Comment by giacomocavalieri** [comment]
I slightly changed the original description to consider the possibility of having other entities rather than only classes: each row of the table could correspond to a Class, an Enum, a case of an enum, a Type, ... rather than calling this field "classes" I'd opt for "rows" which makes clearer you are specifying an entity for each row

**Comment by giacomocavalieri** [comment]
I propose the structure of the file could be the following:

```yaml
tables:
  - name: "Table 1"
    columns: 
      - name: "col1"
        selector: "title"
      - name: "col2"
        selector: "div > p"
      - name: "col3"
        selector: "p"
    mode:
      files:
        - "MyClass"
        - "MyType"
        - "MyEnum"

  - name: "Table 2"
    columns:
      - name: "col1"
        selector: "title"
      - name: "col2"
        selector: "div > p"
      - name: "col3"
        selector: "p"
    mode:
      batch:
        - "dir1"
        - "dir2"
```

```scala
final case class Table(name: String, columns: Seq[Column], mode: Mode)
final case class Column(name: String, selector: String)

sealed trait Mode
final case class Files(files: List[FilePath]) extends Mode
final case class Batch(dirs: List[FilePath]) extends Mode
```

- `tables` is composed of a list of `Table` objects, each one has
  - `name`  the name of the table
  - a list of `Column` objects, each one has 2 fields: a `name` and an html `selector`
  - a `mode` field which can either be
    - an object with a `files` field composed of a list of `String`s, each one is interpreted as a path to an `.html` file and parsed to create a new row in the table
    - an object with a `batch` field composed of a list of `String`s; each one is interpreted as a path to a directory and all `.html` files contained in it will be parsed to create new rows in the table

**Noteworthy**
- If one opts in for the batch mode the rows of the resulting table should be sorted in alphabetical order
- If one opts in for the files mode the rows should appear in the order provided in the `.yaml` file
- If a file or a directory can not be found the plugin should be as loud as possible about it, I think throwing an exception could be the better option here
- There may be several errors:
  - **A file or a directory can not be found:** the plugin should throw an exception, it means an important domain concept we needed is not actually there
  - **An .html file is not parsable:** the plugin should throw an exception, it means an important domain concept will not be added to the table
  - **An .html file:** does not contain any the selectors specified by the columns, here we could either
    - Issue a warning and ignore the file
    - Issue a warning and create an empty row in the table with just the file name
    - Throw an exception: if someone says he wants a row for the file `XYZ` then it should be considered an important domain concept; if the plugin can not create a row for it then it should be as loud as possible and refuse to create the table until the problem is solved
- We need to decide a way to generate the row name, we could either 
  - Simply take the file name and change it from camel case to something more readable splitting the words
  - Let the programmer decide a strategy by providing a plugin key that is a function `FilePath => String` so one can customise the name creation. The default behaviour could still be to split camel case
